import type { Metadata } from "next";
import { BIZ_UDPGothic, Kablammo } from "next/font/google";
import Smooth from "./helpers/Smooth";

export const metadata: Metadata = {
  title: "rjhome2",
  description: "Generated by create next app",
};

const BIZ = BIZ_UDPGothic({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-biz",
});

const Kab = Kablammo({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-kab",
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" style={{ backgroundColor: "black" }}>
      <body className={`${BIZ.variable} ${Kab.variable}`}>
        <Smooth>{children}</Smooth>
      </body>
    </html>
  );
}
